spring.application.name=EcommerceSpring



server.port=${PORT}


#### Database (MySQL) ke sath pipe-line (Connection Pool) setup karne ke liye address aur security keys pradan karna.
#### Industry Production Rule (CRITICAL): Devops aur security standards ke mutabik, kabhi bhi database ka asli password,
# username ya URL direct properties file me type nahi kiya jata. Agar aapne direct password likh kar code GitHub par push kar diya,
# toh company ka data hack ho jayega.
#### Process: ${DB_PASSWORD} ka matlab hai ki asli credentials developer ke laptop ki operating system me ya cloud server (AWS Secrets Manager/Vault) me surakshit save hain.
# Run hote waqt Spring unhe wahan se chupke se utha leta hai.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}


####Spring Boot (Java) aur MySQL database ke beech baat-cheet karwane waale translator (Driver) ka address.
####Spring Boot 3+ me agar aap is line ko na bhi likhein,
# toh bhi Spring Boot dependencies check karke automatic samajh jata hai ki MySQL use ho raha hai.
# Par production me explicit documentation ke liye ise likhna ek safe practice maana jata hai.
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver


####Jab bhi Hibernate internal query chalaye (jaise products fetch karna), toh use aapke IntelliJ ke terminal console par print kare.
#### Industry Process: Development Phase: Ise true rakha jata hai taaki developer debug kar sake ki piche background me sahi SQL chal rahi hai ya nahi.
#### Production Phase (Live Server): Ise strictly false kiya jata hai.
# Agar live server par har second hazaro customers aayenge aur saari queries console par print hoti rahingi,
# toh server ka CPU/Memory fill ho jayega aur performance slow ho jayegi.
spring.jpa.show-sql = true


####Hibernate ko batana ki use kis specific database ki bhasha me SQL query likhni hai.
#### Industry Process: Kyunki MySQL, PostgreSQL, aur Oracle ke SQL syntax me thoda farq hota hai,
# isliye yeh "Dialect" (boli) set karna zaroori hota hai taaki Hibernate sahi dialect me code convert kare.
# (Spring Boot 3 me ab Hibernate automatic dialect detect kar leta hai).
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#### Java me banaye gaye Models/Entities (jaise Product, Category classes) ke mutabik database me tables ko automatic handle karna.
#### Local Development (update): Java me agar aap product me koi nayi field add karoge (jaise image_url), toh database me automatic naya column jud jayega. Purana data delete nahi hota.
#### Production / Live Server (none ya validate): Production par ise update ya create-drop rakhna ek crime (bhadnak galti) maana jata hai! Agar galti se kisi live server par auto-update chala,
# toh tables corrupt ho sakti hain ya pura customer data ud sakta hai. Industry me live database me badlav karne ke liye Flyway ya Liquibase jaise DB Migration tools use kiye jaate hain.
spring.jpa.hibernate.ddl-auto=none

spring.jpa.open-in-view=false



#flyway Migration
spring.flyway.enabled=true

spring.flyway.location=classpath:db/migration

